### ISSUE TITLE
weather text is not working

### ISSUE THREAD

**Issue by siddheshgunjal** [ayoisaiah/weather-bot#1]
I have followed all your steps as mentioned in the article and normal small talks (hi, hello, etc.) are working. But when i ask for weather it just give me small blank chat bubble. i will attach screenshot of the same with this
![screen shot 2018-10-13 at 6 40 34 pm](https://user-images.githubusercontent.com/37741186/46905887-ccaeb800-cf17-11e8-8b4f-29b0f5ebf885.png)
Please help me to resolve this issue.

**Comment by ayoisaiah** [comment]
Hey @siddheshgunjal  were you able to fix this issue?
